#!/bin/bash

set -e

export HOME=/usr/local
sudo mkdir -p $HOME
sudo chown 1000:1000 /usr/local

. /etc/profile
sudo cp /bin/sed /usr/bin/sed

sudo emerge --nodeps sys-devel/autoconf sys-devel/automake sys-devel/autoconf-archive sys-libs/glibc sys-devel/binutils dev-build/libtool sys-apps/util-linux sys-apps/coreutils app-shells/bash dev-lang/perl dev-lang/python
sudo USE="-http2" emerge net-misc/curl dev-vcs/git
sudo emerge -uDN @world sys-process/procps dev-libs/nss media-libs/libjpeg-turbo media-libs/libpng dev-libs/libtasn1 dev-libs/glib dev-util/glib-utils dev-libs/json-glib sys-fs/dosfstools app-arch/cpio sys-fs/ntfs3g sys-apps/flashrom

curl -L https://chromium.googlesource.com/chromiumos/platform/vboot_reference/+archive/refs/heads/release-$chromeos_long_version.tar.gz -o /tmp/cgpt.tar.gz
mkdir /tmp/cgpt
tar zxf /tmp/cgpt.tar.gz -C /tmp/cgpt/
rm -f /tmp/cgpt.tar.gz
cd /tmp/cgpt
make
sudo make install
cd ../..
sudo rm -rf /tmp/cgpt

